apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app: onboarding-microservice-backend
        kompose.cmd: kompose convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: onboarding-microservice-backend
      name: onboarding-microservice-backend
    spec:
      type: NodePort
      ports:
        - name: "5000"
          port: 5000
          targetPort: 80
      selector:
        io.kompose.service: onboarding-microservice-backend
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app: onboarding-microservice-db
        kompose.cmd: kompose convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: onboarding-microservice-db
      name: onboarding-microservice-db
    spec:
      type: ClusterIP
      ports:
        - name: "1433"
          port: 1433
          targetPort: 1433
      selector:
        io.kompose.service: onboarding-microservice-db
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        app: onboarding-microservice-backend
        kompose.cmd: kompose convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: onboarding-microservice-backend
      name: onboarding-microservice-backend
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: onboarding-microservice-backend
        spec:
          containers:
            - env:
                - name: ONBOARDING_URL
                  value: onboarding-api.cureassist.cgi-wave7.stackroute.io
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: sql_server
                  value: server=onboarding-microservice-db;database=DatabasePatient;User Id=sa;Password=Qwerty@123456;
              image: teamcureassist/onboarding-microservice-backend:<VERSION>
              name: onboarding-microservice-backend
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        app: onboarding-microservice-db
        kompose.cmd: kompose convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: onboarding-microservice-db
      name: onboarding-microservice-db
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: onboarding-microservice-db
        spec:
          containers:
            - env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: SA_PASSWORD
                  value: Qwerty@123456
              image: mcr.microsoft.com/mssql/server
              name: onboarding-microservice-db
              ports:
                - containerPort: 1433
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: onboarding-microservice-ingress
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
        - host: onboarding-api.cureassist.cgi-wave7.stackroute.io
          http:
            paths:
              - path: /
                backend:
                  serviceName: onboarding-microservice-backend
                  servicePort: 80
kind: List
metadata: {}
