apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -f docker-compose.yml -o kube-manifest.yaml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: mongodb
    name: mongodb
  spec:
    type: ClusterIP
    ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    selector:
      io.kompose.service: mongodb
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -f docker-compose.yml -o kube-manifest.yaml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: pharmacy-portal-backend
    name: pharmacy-portal-backend
  spec:
    type: NodePort
    ports:
    - name: "5005"
      port: 5005
      targetPort: 80
    selector:
      io.kompose.service: pharmacy-portal-backend
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -f docker-compose.yml -o kube-manifest.yaml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: pharmacy-portal-backend-db
    name: pharmacy-portal-backend-db
  spec:
    type: ClusterIP
    ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
    selector:
      io.kompose.service: pharmacy-portal-backend-db
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -f docker-compose.yml -o kube-manifest.yaml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: mongodb
    name: mongodb
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: mongodb
      spec:
        containers:
        - image: mvertes/alpine-mongo
          name: mongodb
          ports:
          - containerPort: 27017
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -f docker-compose.yml -o kube-manifest.yaml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: pharmacy-portal-backend
    name: pharmacy-portal-backend
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: pharmacy-portal-backend
      spec:
        containers:
        - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: mongodb
            value: mongodb://mongodb:27017
          - name: sql_server
            value: server=pharmacy-portal-backend-db;database=pharmacyDatabase;User Id=sa;Password=Password123;
          image: teamcureassist/pharmacy-portal-backend:<VERSION>
          name: pharmacy-portal-backend
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
        convert -f docker-compose.yml -o kube-manifest.yaml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: pharmacy-portal-backend-db
    name: pharmacy-portal-backend-db
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: pharmacy-portal-backend-db
      spec:
        containers:
        - env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: Password123
          image: mcr.microsoft.com/mssql/server
          name: pharmacy-portal-backend-db
          ports:
          - containerPort: 1433
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: pharmacy-portal-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
    - host: pharmacy-api.cureassist.cgi-wave7.stackroute.io
      http:
        paths:
        - path: /
          backend:
            serviceName: pharmacy-portal-backend
            servicePort: 80
kind: List
metadata: {}