apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd:
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: doctor-dc-backend
      name: doctor-dc-backend
    spec:
      type: NodePort
      ports:
        - name: "5002"
          port: 5002
          targetPort: 80
      selector:
        io.kompose.service: doctor-dc-backend
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd:
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: doctor-dc-backend-db
      name: doctor-dc-backend-db
    spec:
      type: ClusterIP
      ports:
        - name: "27017"
          port: 27017
          targetPort: 27017
      selector:
        io.kompose.service: doctor-dc-backend-db
    status:
      loadBalancer: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd:
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: doctor-dc-backend
      name: doctor-dc-backend
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: doctor-dc-backend
        spec:
          containers:
            - env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: MONGODB_HOST
                  value: mongodb://doctor-dc-backend-db:27017
              image: teamcureassist/doctor-dc-portal-backend:<VERSION>
              name: doctor-dc-backend
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd:
          C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: doctor-dc-backend-db
      name: doctor-dc-backend-db
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: doctor-dc-backend-db
        spec:
          containers:
            - image: mvertes/alpine-mongo
              name: doctor-dc-backend-db
              ports:
                - containerPort: 27017
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: doctor-dc-portal-ingress
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
        - host: doctor-dc-api.cureassist.cgi-wave7.stackroute.io
          http:
            paths:
            - path: /
              backend:
                serviceName: doctor-dc-backend
                servicePort: 80
kind: List
metadata: {}
